name: OnPushNewVersion

on:
  push:    
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
   
      - name: Download release asset
        uses: dsaltares/fetch-gh-release-asset@master
        with:        
          file: SetupKlvStreamInjector.zip
          target: SetupKlvStreamInjector.zip
          # token: ${{ secrets.DEPLOY_TOKEN }}

      - run: echo "🖥️ The version is ready to be uploaded."
      - name: List files in the repository
        run: |
          tree ${{ github.workspace }}

      - name: 📂 Upload KlvStreamInjector to ImpleoTV FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.impleotv.com
          username: sw@impleotv.com
          password: ${{ secrets.FTP_IMPLEO_SW }}
          local-dir: ./
          server-dir: klvstreaminjector/
        